# Generated by Django 2.2.17 on 2021-04-01 13:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc

def add_user_profiles(apps, schema_editor):
    User = apps.get_model('authapp', 'User')
    ShopUserProfile = apps.get_model('authapp', 'ShopUserProfile')

    users = User.objects.all()
    for user in users:
        user_profile = ShopUserProfile.objects.create(user=user)
        user_profile.save()


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_auto_20210401_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 3, 13, 46, 57, 845888, tzinfo=utc)),
        ),
        migrations.RunPython(add_user_profiles),
    ]
